INSERT INTO user_tb(username, password, email, profile, created_at) values('ssar', '937e8d5fbb48bd4949536cd65b8d35c426b80d2f830c5c308e2cdec422ae2244', 'ssar@nate.com','/images/dm.png', now());
INSERT INTO user_tb(username, password, email, profile, created_at) values('love', '937e8d5fbb48bd4949536cd65b8d35c426b80d2f830c5c308e2cdec422ae2244', 'love@nate.com','/images/dm.png', now());


INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('1번째 제목', '1번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('2번째 제목', '2번째 내용','/images/p.jpg', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('3번째 제목', '3번째 검색 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('4번째 제목', '4번째 내용','/images/th.jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('5번째 제목', '5번째 내용','/images/th (14).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('6번째 제목', '6번째 내용','/images/th (13).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('7번째 제목', '7번째 내용','/images/th (12).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('8번째 제목', '8번째 내용','/images/th (11).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('9번째 제목', '9번째 내용','/images/th (10).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('10번째 제목', '10번째 내용','/images/th (9).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('11번째 제목', '11번째 내용','/images/th (8).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('12번째 제목', '12번째 내용','/images/th (7).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('13번째 검색 제목', '13번째 내용','/images/th (6).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('14번째 제목', '14번째 내용','/images/th (5).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('15번째 제목', '15번째 내용','/images/th (4).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('16번째 제목', '16번째 내용','/images/th (3).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('17번째 제목', '17번째 내용','/images/th (2).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('18번째 제목', '18번째 내용','/images/th (1).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('1번째 제목', '1번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('검색 2번째 제목', '2번째 내용','/images/p.jpg', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('3번째 제목', '3번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('4번째 제목', '4번째 내용','/images/th.jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('5번째 제목', '5번째 내용','/images/th (14).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('6번째 제목', '6번째 내용','/images/th (13).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('7번째 제목', '7번째 검색 내용','/images/th (12).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('8번째 제목', '8번째 내용','/images/th (11).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('9번째 제목', '9번째 내용','/images/th (10).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('10번째 제목', '10번째 내용','/images/th (9).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('11번째 제목', '11번째 내용','/images/th (8).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('12번째 제목', '12번째 내용','/images/th (7).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('13번째 제목', '13번째 내용','/images/th (6).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('14번째 제목', '14번째 내용','/images/th (5).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('15번째 제목', '15번째 내용','/images/th (4).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('16번째 제목', '16번째 내용','/images/th (3).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('17번째 제목', '17번째 내용','/images/th (2).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('18번째 제목', '18번째 내용','/images/th (1).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('1번째 제목', '1번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('2번째 제목', '2번째 내용','/images/p.jpg', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('3번째 제목', '3번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('4번째 제목', '4번째 내용','/images/th.jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('5번째 제목', '5번째 내용','/images/th (14).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('6번째 제목', '6번째 내용','/images/th (13).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('7번째 제목', '7번째 내용','/images/th (12).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('8번째 제목', '8번째 내용','/images/th (11).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('9번째 제목', '9번째 내용','/images/th (10).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('10번째 제목', '10번째 내용','/images/th (9).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('11번째 제목', '11번째 내용','/images/th (8).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('12번째 제목', '12번째 내용','/images/th (7).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('13번째 제목', '13번째 내용','/images/th (6).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('14번째 제목', '14번째 내용','/images/th (5).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('15번째 제목', '15번째 내용','/images/th (4).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('16번째 제목', '16번째 내용','/images/th (3).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('17번째 제목', '17번째 내용','/images/th (2).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('18번째 제목', '18번째 내용','/images/th (1).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('1번째 제목', '1번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('2번째 제목', '2번째 내용','/images/p.jpg', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('3번째 제목', '3번째 내용','/images/dm.png', 1, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('4번째 제목', '4번째 내용','/images/th.jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('5번째 제목', '5번째 내용','/images/th (14).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('6번째 제목', '6번째 내용','/images/th (13).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('7번째 제목', '7번째 내용','/images/th (12).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('8번째 제목', '8번째 내용','/images/th (11).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('9번째 제목', '9번째 내용','/images/th (10).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('10번째 제목', '10번째 내용','/images/th (9).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('11번째 제목', '11번째 내용','/images/th (8).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('12번째 제목', '12번째 내용','/images/th (7).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('13번째 제목', '13번째 내용','/images/th (6).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('14번째 제목', '14번째 내용','/images/th (5).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('15번째 제목', '15번째 내용','/images/th (4).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('16번째 제목', '16번째 내용','/images/th (3).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('17번째 제목', '17번째 내용','/images/th (2).jpg', 2, now());
INSERT INTO board_tb(title, content, thumbnail, user_id, created_at) values('18번째 제목', '18번째 내용','/images/th (1).jpg', 2, now());


insert into reply_tb(comment, board_id, user_id, created_at) values('댓글1', 1, 1, now());
insert into reply_tb(comment, board_id, user_id, created_at) values('댓글1', 1, 2, now());
insert into reply_tb(comment, board_id, user_id, created_at) values('댓글1', 2, 1, now());
insert into reply_tb(comment, board_id, user_id, created_at) values('댓글1', 2, 2, now());
insert into reply_tb(comment, board_id, user_id, created_at) values('댓글1', 1, 3, now());
insert into reply_tb(comment, board_id, user_id, created_at) values('댓글1', 2, 3, now());

-- insert into love_tb(board_id,user_id,created_at) values(1,1,now());
-- insert into love_tb(board_id,user_id,created_at) values(1,2,now());

commit;